export const componentExampleModes = {
  "accordion": "expanding",
  "alert-dialog": "overlay",
  "app-bar": "structural",
  "aspect-ratio": "structural",
  "avatar": "compact",
  "badge": "compact",
  "bottom-navigation": "structural",
  "breadcrumb": "structural",
  "button": "compact",
  "card": "structural",
  "checkbox": "compact",
  "checkbox-group": "form",
  "chip": "compact",
  "code": "compact",
  "code-block": "structural",
  "collapsible": "expanding",
  "combobox": "form",
  "container": "structural",
  "context-menu": "interaction",
  "data-grid": "structural",
  "dialog": "overlay",
  "divider": "structural",
  "drawer": "overlay",
  "dropdown-menu": "overlay",
  "feed": "structural",
  "field": "form",
  "fieldset": "form",
  "file-upload": "interaction",
  "form": "form",
  "grid": "structural",
  "hide": "compact",
  "hover-card": "overlay",
  "icon": "compact",
  "icon-button": "compact",
  "image": "structural",
  "input": "form",
  "link": "compact",
  "list": "structural",
  "menubar": "overlay",
  "multi-select": "form",
  "nav-list": "structural",
  "navigation-menu": "expanding",
  "notification-badge": "compact",
  "number-input": "form",
  "otp-field": "form",
  "pagination": "compact",
  "password-toggle-field": "form",
  "popover": "overlay",
  "progress": "form",
  "progress-circle": "compact",
  "radio-group": "form",
  "rating": "compact",
  "scroll-area": "structural",
  "select": "form",
  "show": "compact",
  "sidebar": "structural",
  "skeleton": "structural",
  "skip-link": "interaction",
  "slider": "form",
  "stack": "structural",
  "surface": "structural",
  "swipeable-item": "interaction",
  "switch": "compact",
  "table": "structural",
  "tabs": "structural",
  "text": "compact",
  "textarea": "form",
  "toast": "overlay",
  "toggle": "compact",
  "toggle-group": "compact",
  "toolbar": "structural",
  "tooltip": "overlay",
  "tree": "expanding",
  "tree-grid": "structural",
  "visually-hidden": "interaction",
} as const;

export type ComponentExampleMode = (typeof componentExampleModes)[keyof typeof componentExampleModes];

export function componentExampleMode(slug: string): ComponentExampleMode {
  return componentExampleModes[slug as keyof typeof componentExampleModes] ?? "compact";
}
