"use client";

import dynamic from "next/dynamic";
import { Text } from "@flowstack-ui/brick/text";

const previews = {
  "accordion": dynamic(() => import("@/components/previews/accordion")),
  "alert-dialog": dynamic(() => import("@/components/previews/alert-dialog")),
  "app-bar": dynamic(() => import("@/components/previews/app-bar")),
  "appearance": dynamic(() => import("@/components/previews/appearance")),
  "aspect-ratio": dynamic(() => import("@/components/previews/aspect-ratio")),
  "avatar": dynamic(() => import("@/components/previews/avatar")),
  "badge": dynamic(() => import("@/components/previews/badge")),
  "bleed": dynamic(() => import("@/components/previews/bleed")),
  "blockquote": dynamic(() => import("@/components/previews/blockquote")),
  "bottom-navigation": dynamic(() => import("@/components/previews/bottom-navigation")),
  "breadcrumb": dynamic(() => import("@/components/previews/breadcrumb")),
  "button": dynamic(() => import("@/components/previews/button")),
  "card": dynamic(() => import("@/components/previews/card")),
  "carousel": dynamic(() => import("@/components/previews/carousel")),
  "checkbox": dynamic(() => import("@/components/previews/checkbox")),
  "checkbox-group": dynamic(() => import("@/components/previews/checkbox-group")),
  "chip": dynamic(() => import("@/components/previews/chip")),
  "code": dynamic(() => import("@/components/previews/code")),
  "code-block": dynamic(() => import("@/components/previews/code-block")),
  "color-picker": dynamic(() => import("@/components/previews/color-picker")),
  "color-swatch": dynamic(() => import("@/components/previews/color-swatch")),
  "collapsible": dynamic(() => import("@/components/previews/collapsible")),
  "combobox": dynamic(() => import("@/components/previews/combobox")),
  "container": dynamic(() => import("@/components/previews/container")),
  "context-menu": dynamic(() => import("@/components/previews/context-menu")),
  "data-grid": dynamic(() => import("@/components/previews/data-grid")),
  "data-list": dynamic(() => import("@/components/previews/data-list")),
  "dialog": dynamic(() => import("@/components/previews/dialog")),
  "divider": dynamic(() => import("@/components/previews/divider")),
  "drawer": dynamic(() => import("@/components/previews/drawer")),
  "dropdown-menu": dynamic(() => import("@/components/previews/dropdown-menu")),
  "em": dynamic(() => import("@/components/previews/em")),
  "feed": dynamic(() => import("@/components/previews/feed")),
  "field": dynamic(() => import("@/components/previews/field")),
  "fieldset": dynamic(() => import("@/components/previews/fieldset")),
  "file-upload": dynamic(() => import("@/components/previews/file-upload")),
  "form": dynamic(() => import("@/components/previews/form")),
  "frame": dynamic(() => import("@/components/previews/frame")),
  "grid": dynamic(() => import("@/components/previews/grid")),
  "group": dynamic(() => import("@/components/previews/group")),
  "hide": dynamic(() => import("@/components/previews/hide")),
  "highlight": dynamic(() => import("@/components/previews/highlight")),
  "hover-card": dynamic(() => import("@/components/previews/hover-card")),
  "icon": dynamic(() => import("@/components/previews/icon")),
  "icon-button": dynamic(() => import("@/components/previews/icon-button")),
  "image": dynamic(() => import("@/components/previews/image")),
  "input": dynamic(() => import("@/components/previews/input")),
  "kbd": dynamic(() => import("@/components/previews/kbd")),
  "link": dynamic(() => import("@/components/previews/link")),
  "link-box": dynamic(() => import("@/components/previews/link-box")),
  "list": dynamic(() => import("@/components/previews/list")),
  "menubar": dynamic(() => import("@/components/previews/menubar")),
  "mark": dynamic(() => import("@/components/previews/mark")),
  "multi-select": dynamic(() => import("@/components/previews/multi-select")),
  "nav-list": dynamic(() => import("@/components/previews/nav-list")),
  "navigation-menu": dynamic(() => import("@/components/previews/navigation-menu")),
  "notification-badge": dynamic(() => import("@/components/previews/notification-badge")),
  "number-input": dynamic(() => import("@/components/previews/number-input")),
  "otp-field": dynamic(() => import("@/components/previews/otp-field")),
  "pagination": dynamic(() => import("@/components/previews/pagination")),
  "password-toggle-field": dynamic(() => import("@/components/previews/password-toggle-field")),
  "popover": dynamic(() => import("@/components/previews/popover")),
  "progress": dynamic(() => import("@/components/previews/progress")),
  "progress-circle": dynamic(() => import("@/components/previews/progress-circle")),
  "prose": dynamic(() => import("@/components/previews/prose")),
  "radio-group": dynamic(() => import("@/components/previews/radio-group")),
  "rating": dynamic(() => import("@/components/previews/rating")),
  "rich-text-editor": dynamic(() => import("@/components/previews/rich-text-editor")),
  "reorderable-list": dynamic(() => import("@/components/previews/reorderable-list")),
  "scroll-area": dynamic(() => import("@/components/previews/scroll-area")),
  "section": dynamic(() => import("@/components/previews/section")),
  "select": dynamic(() => import("@/components/previews/select")),
  "segment-group": dynamic(() => import("@/components/previews/segment-group")),
  "show": dynamic(() => import("@/components/previews/show")),
  "sidebar": dynamic(() => import("@/components/previews/sidebar")),
  "skeleton": dynamic(() => import("@/components/previews/skeleton")),
  "skip-link": dynamic(() => import("@/components/previews/skip-link")),
  "slider": dynamic(() => import("@/components/previews/slider")),
  "stack": dynamic(() => import("@/components/previews/stack")),
  "status": dynamic(() => import("@/components/previews/status")),
  "surface": dynamic(() => import("@/components/previews/surface")),
  "swipeable-item": dynamic(() => import("@/components/previews/swipeable-item")),
  "switch": dynamic(() => import("@/components/previews/switch")),
  "table": dynamic(() => import("@/components/previews/table")),
  "tabs": dynamic(() => import("@/components/previews/tabs")),
  "text": dynamic(() => import("@/components/previews/text")),
  "textarea": dynamic(() => import("@/components/previews/textarea")),
  "toast": dynamic(() => import("@/components/previews/toast")),
  "toggle": dynamic(() => import("@/components/previews/toggle")),
  "toggle-group": dynamic(() => import("@/components/previews/toggle-group")),
  "toolbar": dynamic(() => import("@/components/previews/toolbar")),
  "tooltip": dynamic(() => import("@/components/previews/tooltip")),
  "tree": dynamic(() => import("@/components/previews/tree")),
  "tree-grid": dynamic(() => import("@/components/previews/tree-grid")),
  "visually-hidden": dynamic(() => import("@/components/previews/visually-hidden")),
  "z-stack": dynamic(() => import("@/components/previews/z-stack")),
} as const;

function UnknownPreview({ slug }: { slug: string }) {
  return <Text>Missing preview for {slug}</Text>;
}

export function ComponentPreview({ slug }: { slug: string }) {
  const Preview = previews[slug as keyof typeof previews];
  return Preview ? <Preview /> : <UnknownPreview slug={slug} />;
}
